# Generated by Django 3.1.4 on 2020-12-08 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20)),
                ('ticket_price', models.FloatField()),
                ('threshold_price', models.FloatField()),
                ('current_passenger', models.IntegerField()),
                ('threshold_passenger', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_start', models.CharField(max_length=50)),
                ('station_end', models.CharField(max_length=50)),
                ('estimate_hour', models.IntegerField()),
                ('estimate_minute', models.IntegerField()),
                ('start_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('start_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('end_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('end_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('base_order_number', models.UUIDField()),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('payment', models.FloatField()),
                ('status', models.IntegerField()),
                ('bus_start_time', models.DateTimeField()),
                ('bus_end_time', models.DateTimeField()),
                ('station_start', models.CharField(max_length=50)),
                ('station_end', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hibus.bus')),
                ('line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hibus.line')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='line_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hibus.line'),
        ),
    ]
