# Generated by Django 3.1.4 on 2020-12-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='base_order_number',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(),
        ),
    ]
