# Generated by Django 3.1.4 on 2020-12-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='end_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='end_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='line',
            name='end_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='start_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='line',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
